export type ApiHttpErrorCode =
  | 'INVALID_COMPANY_ID'
  | 'INVALID_PATH_PARAMETER'
  | 'INVALID_QUERY_PARAMETER'
  | 'INVALID_CURSOR'
  | 'INVALID_REQUEST_BODY'
  | 'COMPANY_CONTEXT_REQUIRED'
  | 'COMPANY_CONTEXT_MISMATCH'
  | 'COMPANY_NOT_FOUND'
  | 'COMPANY_SLUG_CONFLICT'
  | 'COMPANY_STATUS_UNCHANGED'
  | 'COMPANY_STATUS_TRANSITION_INVALID'
  | 'COMPANY_STATUS_CONFLICT'
  | 'MEMBERSHIP_NOT_FOUND'
  | 'MEMBERSHIP_CONFLICT'
  | 'SELF_MEMBERSHIP_CHANGE_FORBIDDEN'
  | 'USER_NOT_FOUND'
  | 'USER_STATUS_UNCHANGED'
  | 'USER_STATUS_CONFLICT'
  | 'SELF_USER_SUSPENSION_FORBIDDEN'
  | 'BILLING_PLAN_NOT_FOUND'
  | 'BILLING_PLAN_CODE_CONFLICT'
  | 'BILLING_PLAN_ARCHIVED'
  | 'BILLING_PLAN_UNCHANGED'
  | 'BILLING_PLAN_IN_USE'
  | 'BILLING_PLAN_UPDATE_CONFLICT'
  | 'BILLING_ENTITLEMENT_KEY_CONFLICT'
  | 'BILLING_COMPANY_ARCHIVED'
  | 'BILLING_SUBSCRIPTION_CONFLICT'
  | 'BILLING_SUBSCRIPTION_NOT_FOUND'
  | 'BILLING_SUBSCRIPTION_TERMINAL'
  | 'BILLING_SUBSCRIPTION_TRANSITION_INVALID'
  | 'BILLING_SUBSCRIPTION_DATE_INVALID'
  | 'BILLING_SUBSCRIPTION_UNCHANGED'
  | 'BILLING_SUBSCRIPTION_UPDATE_CONFLICT'
  | 'TRACKING_NETWORK_COMPANY_INACTIVE'
  | 'TRACKING_DOMAIN_NOT_FOUND'
  | 'TRACKING_DOMAIN_HOSTNAME_CONFLICT'
  | 'TRACKING_DOMAIN_ARCHIVED'
  | 'TRACKING_DOMAIN_HOSTNAME_LOCKED'
  | 'TRACKING_DOMAIN_UNVERIFIED'
  | 'TRACKING_DOMAIN_UNCHANGED'
  | 'TRACKING_DOMAIN_UPDATE_CONFLICT'
  | 'NETWORK_PROVIDER_NOT_FOUND'
  | 'NETWORK_PROVIDER_CODE_CONFLICT'
  | 'NETWORK_PROVIDER_ARCHIVED'
  | 'NETWORK_PROVIDER_IN_USE'
  | 'NETWORK_PROVIDER_UNCHANGED'
  | 'NETWORK_PROVIDER_UPDATE_CONFLICT'
  | 'NETWORK_ACCOUNT_NOT_FOUND'
  | 'NETWORK_ACCOUNT_CONFLICT'
  | 'NETWORK_ACCOUNT_ARCHIVED'
  | 'NETWORK_ACCOUNT_UNCHANGED'
  | 'NETWORK_ACCOUNT_STATUS_TRANSITION_INVALID'
  | 'NETWORK_ACCOUNT_UPDATE_CONFLICT';

export interface ApiHttpErrorOptions {
  readonly cause?: unknown;
}

function createNativeErrorOptions(cause: unknown): ErrorOptions | undefined {
  return cause === undefined
    ? undefined
    : {
        cause,
      };
}

export class ApiHttpError extends Error {
  public constructor(
    public readonly code: ApiHttpErrorCode,
    public readonly statusCode: number,
    message: string,
    options: ApiHttpErrorOptions = {},
  ) {
    const normalizedMessage = message.trim();

    super(
      normalizedMessage.length > 0 ? normalizedMessage : 'The HTTP request is invalid.',
      createNativeErrorOptions(options.cause),
    );

    this.name = 'ApiHttpError';
  }
}
